config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Authentication / Authorizat
  use_doorkeeper
  use_doorkeeper_openid_connect
  devise_for :users
  get '.well-known/app.json', controller: :well_known, action: :app
  get '.well-known/terraform.json', controller: :well_known, action: :terraform
  get 'github/setup', controller: :github, action: :setup

  get 'app/*_', controller: :application, action: :index

  # Registry Routes
  namespace :registry, defaults: { format: :json } do
    namespace :v1 do
      scope 'modules', controller: 'modules' do
        get '/', action: :index
        get '/:namespace', action: :index
        get '/search', action: :search
        get '/:namespace/:name/:provider/versions', action: :versions
        get '/:namespace/:name/:provider/:version/download', action: :download, constraints: { version: %r{[^/]+} }
        get '/archive/:namespace/:name/:provider/:version/*.tar.gz', action: :archive, as: :archive,
                                                                     constraints: { version: %r{[^/]+} }
        get '/:namespace/:name/:provider/download', action: :download
        get '/:namespace/:name', action: :latest
        get '/:namespace/:name/:provider', action: :latest
        get '/:namespace/:name/:provider/:version', action: :show, constraints: { version: %r{[^/]+} }
        post '/:namespace/:name/:provider/:version', action: :create, constraints: { version: %r{[^/]+} }
      end
      scope 'providers', controller: 'providers' do
        post '/:namespace/:type/:version', action: :create, constraints: { version: %r{[^/]+} }
        get '/:namespace/:type/versions', action: :index
      end
    end
  end

  # API Routes
  namespace :api, defaults: { format: :json } do
    namespace :v2 do
      post :webhooks, action: :create, controller: 'webhooks'
      get :ping, action: :ping, controller: 'ping'
      get 'account/details', action: :show, controller: :account_details
      get 'organizations', action: :index, controller: :organizations
      get 'object/:key', action: :show, controller: :storage, as: :get_storage
      put 'object/:key', action: :update, controller: :storage, as: :upload_storage
      post 'organizations', action: :create, controller: :organizations
      scope '/organizations/:organization_id', as: :organization do
        get '', action: :show, controller: :organizations
        patch '', action: :update, controller: :organizations
        get 'entitlement-set', action: :entitlements, controller: :organizations
        get 'workspaces', action: :index, controller: :workspaces
        get 'workspaces/:id', action: :show, controller: :workspaces
        get 'runs/queue', action: :queue, controller: :organizations
        match 'tags', via: %i[get post delete], controller: :organizations

        get 'agent-pools', action: :index, controller: 'agents'
        post 'agent-pools', action: :create, controller: 'agents'

        get 'cloud-providers', action: :index, controller: :cloud_providers
        post 'cloud-providers', action: :create, controller: :cloud_providers

        get 'tasks', action: :index, controller: 'run_tasks'
        post 'tasks', action: :create, controller: 'run_tasks'

        get 'projects', action: :index, controller: :projects
        post 'projects', action: :create, controller: :projects

        get 'teams', action: :index, controller: :teams
        post 'teams', action: :create, controller: :teams

        get 'varsets', action: :index, controller: :variable_sets
        post 'varsets', action: :create, controller: :variable_sets

        get 'policies', action: :index, controller: :policies
        post 'policies', action: :create, controller: :policies

        post 'organization-memberships', action: :create, controller: :organization_memberships
        get 'organization-memberships', action: :index, controller: :organization_memberships

        post 'oauth-clients', action: :create, controller: :oauth_clients
        get 'oauth-clients', action: :index, controller: :oauth_clients

        post :workspaces, action: :create, controller: :workspaces

        get 'ssh-keys', action: :index, controller: :ssh_keys
        post 'ssh-keys', action: :create, controller: :ssh_keys

        get 'team-tokens', action: :list_team_tokens, controller: :authentication_tokens
        post 'authentication-token', action: :create_organization_token, controller: :authentication_tokens
        get 'authentication-token', action: :get_organization_token, controller: :authentication_tokens

        # Routes for registry modules
        get 'registry-modules', action: :index, controller: :modules
        post 'registry-modules', action: :create, controller: :modules
        get 'registry-modules/private/:namespace/:name/:provider', action: :show, controller: :modules, as: :show_module
        patch 'registry-modules/private/:namespace/:name/:provider', action: :update, controller: :modules
        post 'registry-modules/private/:namespace/:name/:provider/versions', action: :create,
                                                                             controller: :module_versions, as: :module_versions
        delete 'registry-modules/private/:namespace/:name', action: :destroy, controller: :modules
        delete 'registry-modules/private/:namespace/:name/:provider', action: :destroy,
                                                                      controller: :modules
        delete 'registry-modules/private/:namespace/:name/:provider/:version', action: :destroy,
                                                                               controller: :module_versions
        # Routes for registry providers
        get 'registry-providers', action: :index, controller: :providers
        post 'registry-providers', action: :create, controller: :providers
        get 'registry-providers/private/:namespace/:name', action: :show, controller: :providers
        delete 'registry-providers/:registry_name/:namespace/:name', action: :destroy,
                                                                     controller: :providers
        get 'registry-providers/private/:namespace/:name/versions/', action: :index,
                                                                     controller: :provider_versions, as: :provider_versions
        post 'registry-providers/private/:namespace/:name/versions', action: :create,
                                                                     controller: :provider_versions
        get 'registry-providers/private/:namespace/:name/versions/:version', action: :show,
                                                                             controller: :provider_versions, as: :provider_version
        delete 'registry-providers/private/:namespace/:name/versions/:provider_version', action: :destroy,
                                                                                         controller: :provider_versions
        post 'registry-providers/private/:namespace/:name/versions/:version/platforms', action: :create,
                                                                                        controller: :provider_version_platforms, constraints: { version: %r{[^/]+} }
        get 'registry-providers/private/:namespace/:name/versions/:version/platforms', action: :index,
                                                                                       controller: :provider_version_platforms, constraints: { version: %r{[^/]+} }, as: :provider_version_platforms
        get 'registry-providers/private/:namespace/:name/versions/:version/platforms/:os/:arch', action: :show,
                                                                                                 controller: :provider_version_platforms, constraints: { version: %r{[^/]+} }
        delete 'registry-providers/private/:namespace/:name/versions/:version/platforms/:os/:arch', action: :destroy,
                                                                                                    controller: :provider_version_platforms, constraints: { version: %r{[^/]+} }
      end
      get 'authentication-tokens/:token_id', action: :show, controller: :authentication_tokens
      delete 'authentication-tokens/:token_id', action: :destroy, controller: :authentication_tokens
      get 'state-versions/:id', action: :show, controller: :state_versions
      get 'state-version-outputs/:id', action: :show, controller: :state_version_outputs

      resources :workspaces, except: %i[index create] do
        member do
          post 'actions/lock', action: :lock, controller: :workspaces
          post 'actions/unlock', action: :unlock, controller: :workspaces
          post 'actions/force-unlock', action: :force_unlock, controller: :workspaces

          get 'state-versions', action: :index, controller: :state_versions
          post 'state-versions', action: :create, controller: :state_versions
          get 'current-state-version', action: :current, controller: :state_versions
          get 'current-state-version-outputs', action: :current_outputs, controller: :state_versions
          match 'relationships/tags', via: %i[get post delete], action: :tags, controller: :workspaces
          get :runs
          post :configuration_versions, action: :create, controller: :configuration_versions,
                                        path: 'configuration-versions'

          get :run_triggers, action: :index, path: 'run-triggers', controller: :run_triggers
          post :run_triggers, action: :create, path: 'run-triggers', controller: :run_triggers

          get :notification_configurations, action: :index, path: 'notification-configurations',
                                            controller: :notification_configurations
          post :notification_configurations, action: :create, path: 'notification-configurations',

app/views/partials/_navbar_link.html.erb
<div class="nav-item-wrapper">
  <a class="nav-link label-1" href="<%= path %>" role="button" data-bs-toggle="" aria-expanded="false">
    <div class="d-flex align-items-center">
      <span class="nav-link-icon">
        <span data-feather="compass"></span>
      </span>
      <span class="nav-link-text-wrapper">
        <span class="nav-link-text">
          <%= label %>
        </span>
      </span>
    </div>
  </a>
</div>

app/views/partials/_settings_sidebar.html.erb
<div class="drawer lg:drawer-open">
  <input id="my-drawer-2" type="checkbox" class="drawer-toggle" />
  <div class="drawer-content flex flex-col m-5">
    <%= yield %>
  </div>
  <div class="drawer-side">
    <label for="my-drawer-2" aria-label="close sidebar" class="drawer-overlay"></label>
    <ul class="menu p-4 w-60 min-h-full bg-base-100 border-r border-l text-base-content">
      <!-- Sidebar content here -->
      <li><a href="<%= access_tokens_path %>">Access Tokens</a></li>
      <li><a href="#">Account</a></li>
      <li><a href="">Billing</a></li>
    </ul>

  </div>
</div>

app/views/partials/_sidebar.html.erb
<div class="drawer lg:drawer-open">
  <input id="my-drawer-2" type="checkbox" class="drawer-toggle" />
  <div class="drawer-content flex flex-col m-5">
    <%= yield %>
  </div>
  <div class="drawer-side">
    <ul class="menu p-4 w-60 min-h-full bg-base-100 border-r border-l  text-base-content">
      <li>
        <details>
          <summary>
            <a href="<%= workspaces_path %>">Workspaces</a>
          </summary>
          <% if @workspace.present? && !@workspace.new_record? %>
          <ul>
            <li><a href="<%= workspace_path @workspace %>">Workspace</a></li>
            <li><a href="<%= workspace_runs_path @workspace %>">Runs</a></li>
            <li><a href="<%= new_variable_path(:workspace => @workspace.id, :type => "workspace") %>">Variables</a></li>
            <li><a>Managed Resources</a></li>
            <li><a>Settings</a></li>
          </ul>
          <% end %>
        </details>
      </li>
      <li>
        <a href="<%= vcs_connections_path %>">VCS Connections</a>
      </li>
      <li>
        <a href="">Registry</a>
      </li>
      <li>
        <a href="<%= agents_path %>">Agents</a>
      </li>
      <li>
        <details>
          <summary>
            <a href="<%= organizations_path %>">Organizations</a>
          </summary>
          <% if @organization %>
            <ul>
              <li><a>Users</a></li>
              <li><a>Teams</a></li>
              <li><a>Settings</a></li>
            </ul>
          <% end %>
        </details>
      </li>
      <li>
        <details>
          <summary>
            <a href="<%= policies_path %>">Policies</a>
          </summary>
          <ul>
            <li>
              <a href="<%= policy_sets_path %>">Policy Sets</a>
            </li>
          </ul>
        </details>
      </li>
      <li>
        <details>
          <summary>
            <a href="<%= variables_path %>">Variables</a>
          </summary>
          <ul>
            <li><a>Variable Sets</a></li>
          </ul>
        </details>
      </li>
    </ul>
  </div>
</div>

app/views/partials/_support_container.html.erb
<div class="support-chat-container">
  <div class="container-fluid support-chat">
    <div class="card bg-body-emphasis">
      <div class="card-header d-flex flex-between-center px-4 py-3 border-bottom border-translucent">
        <h5 class="mb-0 d-flex align-items-center gap-2">Demo widget<span class="fa-solid fa-circle text-success fs-11"></span></h5>
        <div class="btn-reveal-trigger">
          <button class="btn btn-link p-0 dropdown-toggle dropdown-caret-none transition-none d-flex" type="button" id="support-chat-dropdown" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true" aria-expanded="false" data-bs-reference="parent"><span class="fas fa-ellipsis-h text-body"></span></button>
          <div class="dropdown-menu dropdown-menu-end py-2" aria-labelledby="support-chat-dropdown"><a class="dropdown-item" href="#!">Request a callback</a><a class="dropdown-item" href="#!">Search in chat</a><a class="dropdown-item" href="#!">Show history</a><a class="dropdown-item" href="#!">Report to Admin</a><a class="dropdown-item btn-support-chat" href="#!">Close Support</a></div>
        </div>
      </div>
      <div class="card-body chat p-0">
        <div class="d-flex flex-column-reverse scrollbar h-100 p-3">
          <div class="text-end mt-6"><a class="mb-2 d-inline-flex align-items-center text-decoration-none text-body-emphasis bg-body-hover rounded-pill border border-primary py-2 ps-4 pe-3" href="#!">
            <p class="mb-0 fw-semibold fs-9">I need help with something</p><span class="fa-solid fa-paper-plane text-primary fs-9 ms-3"></span>
          </a><a class="mb-2 d-inline-flex align-items-center text-decoration-none text-body-emphasis bg-body-hover rounded-pill border border-primary py-2 ps-4 pe-3" href="#!">
            <p class="mb-0 fw-semibold fs-9">I can’t reorder a product I previously ordered</p><span class="fa-solid fa-paper-plane text-primary fs-9 ms-3"></span>
          </a><a class="mb-2 d-inline-flex align-items-center text-decoration-none text-body-emphasis bg-body-hover rounded-pill border border-primary py-2 ps-4 pe-3" href="#!">
            <p class="mb-0 fw-semibold fs-9">How do I place an order?</p><span class="fa-solid fa-paper-plane text-primary fs-9 ms-3"></span>
          </a><a class="false d-inline-flex align-items-center text-decoration-none text-body-emphasis bg-body-hover rounded-pill border border-primary py-2 ps-4 pe-3" href="#!">
            <p class="mb-0 fw-semibold fs-9">My payment method not working</p><span class="fa-solid fa-paper-plane text-primary fs-9 ms-3"></span>
          </a>
          </div>
          <div class="text-center mt-auto">
            <div class="avatar avatar-3xl status-online"><img class="rounded-circle border border-3 border-light-subtle" src="/_vendor/img/team/30.webp" alt="" /></div>
            <h5 class="mt-2 mb-3">Eric</h5>
            <p class="text-center text-body-emphasis mb-0">Ask us anything – we’ll get back to you here or by email within 24 hours.</p>
          </div>
        </div>
      </div>
      <div class="card-footer d-flex align-items-center gap-2 border-top border-translucent ps-3 pe-4 py-3">
        <div class="d-flex align-items-center flex-1 gap-3 border border-translucent rounded-pill px-4">
          <input class="form-control outline-none border-0 flex-1 fs-9 px-0" type="text" placeholder="Write message" />
          <label class="btn btn-link d-flex p-0 text-body-quaternary fs-9 border-0" for="supportChatPhotos"><span class="fa-solid fa-image"></span></label>
          <input class="d-none" type="file" accept="image/*" id="supportChatPhotos" />
          <label class="btn btn-link d-flex p-0 text-body-quaternary fs-9 border-0" for="supportChatAttachment"> <span class="fa-solid fa-paperclip"></span></label>
          <input class="d-none" type="file" id="supportChatAttachment" />
        </div>
        <button class="btn p-0 border-0 send-btn"><span class="fa-solid fa-paper-plane fs-9"></span></button>
      </div>
    </div>
  </div>
  <button class="btn btn-support-chat p-0 border border-translucent"><span class="fs-8 btn-text text-primary text-nowrap">Chat demo</span><span class="ping-icon-wrapper mt-n4 ms-n6 mt-sm-0 ms-sm-2 position-absolute position-sm-relative"><span class="ping-icon-bg"></span><span class="fa-solid fa-circle ping-icon"></span></span><span class="fa-solid fa-headset text-primary fs-8 d-sm-none"></span><span class="fa-solid fa-chevron-down text-primary fs-7"></span></button>
</div>