config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Authentication / Authorizat
  use_doorkeeper
  use_doorkeeper_openid_connect
  devise_for :users
  get '.well-known/app.json', controller: :well_known, action: :app
  get '.well-known/terraform.json', controller: :well_known, action: :terraform
  get 'github/setup', controller: :github, action: :setup

  get 'app/*_', controller: :application, action: :index

  # Registry Routes
  namespace :registry, defaults: { format: :json } do
    namespace :v1 do
      scope 'modules', controller: 'modules' do
        get '/', action: :index
        get '/:namespace', action: :index
        get '/search', action: :search
        get '/:namespace/:name/:provider/versions', action: :versions
        get '/:namespace/:name/:provider/:version/download', action: :download, constraints: { version: %r{[^/]+} }
        get '/archive/:namespace/:name/:provider/:version/*.tar.gz', action: :archive, as: :archive,
                                                                     constraints: { version: %r{[^/]+} }
        get '/:namespace/:name/:provider/download', action: :download
        get '/:namespace/:name', action: :latest
        get '/:namespace/:name/:provider', action: :latest
        get '/:namespace/:name/:provider/:version', action: :show, constraints: { version: %r{[^/]+} }
        post '/:namespace/:name/:provider/:version', action: :create, constraints: { version: %r{[^/]+} }
      end
      scope 'providers', controller: 'providers' do
        post '/:namespace/:type/:version', action: :create, constraints: { version: %r{[^/]+} }
        get '/:namespace/:type/versions', action: :index
      end
    end
  end

  # API Routes
  namespace :api, defaults: { format: :json } do
    namespace :v2 do
      post :webhooks, action: :create, controller: 'webhooks'
      get :ping, action: :ping, controller: 'ping'
      get 'account/details', action: :show, controller: :account_details
      get 'organizations', action: :index, controller: :organizations
      get 'object/:key', action: :show, controller: :storage, as: :get_storage
      put 'object/:key', action: :update, controller: :storage, as: :upload_storage
      post 'organizations', action: :create, controller: :organizations
      scope '/organizations/:organization_id', as: :organization do
        get '', action: :show, controller: :organizations
        patch '', action: :update, controller: :organizations
        get 'entitlement-set', action: :entitlements, controller: :organizations
        get 'workspaces', action: :index, controller: :workspaces
        get 'workspaces/:id', action: :show, controller: :workspaces
        get 'runs/queue', action: :queue, controller: :organizations
        match 'tags', via: %i[get post delete], controller: :organizations

        get 'agent-pools', action: :index, controller: 'agents'
        post 'agent-pools', action: :create, controller: 'agents'

        get 'cloud-providers', action: :index, controller: :cloud_providers
        post 'cloud-providers', action: :create, controller: :cloud_providers

        get 'tasks', action: :index, controller: 'run_tasks'
        post 'tasks', action: :create, controller: 'run_tasks'

        get 'projects', action: :index, controller: :projects
        post 'projects', action: :create, controller: :projects

        get 'teams', action: :index, controller: :teams
        post 'teams', action: :create, controller: :teams

        get 'varsets', action: :index, controller: :variable_sets
        post 'varsets', action: :create, controller: :variable_sets

        get 'policies', action: :index, controller: :policies
        post 'policies', action: :create, controller: :policies

        post 'organization-memberships', action: :create, controller: :organization_memberships
        get 'organization-memberships', action: :index, controller: :organization_memberships

        post 'oauth-clients', action: :create, controller: :oauth_clients
        get 'oauth-clients', action: :index, controller: :oauth_clients

        post :workspaces, action: :create, controller: :workspaces

        get 'ssh-keys', action: :index, controller: :ssh_keys
        post 'ssh-keys', action: :create, controller: :ssh_keys

        get 'team-tokens', action: :list_team_tokens, controller: :authentication_tokens
        post 'authentication-token', action: :create_organization_token, controller: :authentication_tokens
        get 'authentication-token', action: :get_organization_token, controller: :authentication_tokens

        # Routes for registry modules
        get 'registry-modules', action: :index, controller: :modules
        post 'registry-modules', action: :create, controller: :modules
        get 'registry-modules/private/:namespace/:name/:provider', action: :show, controller: :modules, as: :show_module
        patch 'registry-modules/private/:namespace/:name/:provider', action: :update, controller: :modules
        post 'registry-modules/private/:namespace/:name/:provider/versions', action: :create,
                                                                             controller: :module_versions, as: :module_versions
        delete 'registry-modules/private/:namespace/:name', action: :destroy, controller: :modules
        delete 'registry-modules/private/:namespace/:name/:provider', action: :destroy,
                                                                      controller: :modules
        delete 'registry-modules/private/:namespace/:name/:provider/:version', action: :destroy,
                                                                               controller: :module_versions
        # Routes for registry providers
        get 'registry-providers', action: :index, controller: :providers
        post 'registry-providers', action: :create, controller: :providers
        get 'registry-providers/private/:namespace/:name', action: :show, controller: :providers
        delete 'registry-providers/:registry_name/:namespace/:name', action: :destroy,
                                                                     controller: :providers
        get 'registry-providers/private/:namespace/:name/versions/', action: :index,
                                                                     controller: :provider_versions, as: :provider_versions
        post 'registry-providers/private/:namespace/:name/versions', action: :create,
                                                                     controller: :provider_versions
        get 'registry-providers/private/:namespace/:name/versions/:version', action: :show,
                                                                             controller: :provider_versions, as: :provider_version
        delete 'registry-providers/private/:namespace/:name/versions/:provider_version', action: :destroy,
                                                                                         controller: :provider_versions
        post 'registry-providers/private/:namespace/:name/versions/:version/platforms', action: :create,
                                                                                        controller: :provider_version_platforms, constraints: { version: %r{[^/]+} }
        get 'registry-providers/private/:namespace/:name/versions/:version/platforms', action: :index,
                                                                                       controller: :provider_version_platforms, constraints: { version: %r{[^/]+} }, as: :provider_version_platforms
        get 'registry-providers/private/:namespace/:name/versions/:version/platforms/:os/:arch', action: :show,
                                                                                                 controller: :provider_version_platforms, constraints: { version: %r{[^/]+} }
        delete 'registry-providers/private/:namespace/:name/versions/:version/platforms/:os/:arch', action: :destroy,
                                                                                                    controller: :provider_version_platforms, constraints: { version: %r{[^/]+} }
      end
      get 'authentication-tokens/:token_id', action: :show, controller: :authentication_tokens
      delete 'authentication-tokens/:token_id', action: :destroy, controller: :authentication_tokens
      get 'state-versions/:id', action: :show, controller: :state_versions
      get 'state-version-outputs/:id', action: :show, controller: :state_version_outputs

      resources :workspaces, except: %i[index create] do
        member do
          post 'actions/lock', action: :lock, controller: :workspaces
          post 'actions/unlock', action: :unlock, controller: :workspaces
          post 'actions/force-unlock', action: :force_unlock, controller: :workspaces

          get 'state-versions', action: :index, controller: :state_versions
          post 'state-versions', action: :create, controller: :state_versions
          get 'current-state-version', action: :current, controller: :state_versions
          get 'current-state-version-outputs', action: :current_outputs, controller: :state_versions
          match 'relationships/tags', via: %i[get post delete], action: :tags, controller: :workspaces
          get :runs
          post :configuration_versions, action: :create, controller: :configuration_versions,
                                        path: 'configuration-versions'

          get :run_triggers, action: :index, path: 'run-triggers', controller: :run_triggers
          post :run_triggers, action: :create, path: 'run-triggers', controller: :run_triggers

          get :notification_configurations, action: :index, path: 'notification-configurations',
                                            controller: :notification_configurations
          post :notification_configurations, action: :create, path: 'notification-configurations',

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :organization

  has_many :team_projects
  has_many :teams, through: :team_projects

  before_create -> { generate_id('prj') }
end

app/controllers/api/v2/projects_controller.rb
# frozen_string_literal: true

module Api
  module V2
    class ProjectsController < Api::ApiController
      def index
        @org = Organization.find_by(name: params[:organization_id])
        authorize! @org, to: :read?

        @projects = @org.projects
        render json: ::ProjectSerializer.new(@projects, {}).serializable_hash
      end

      def show
        @project = Project.find_by(external_id: params[:id])
        unless @project
          skip_verify_authorized!
          head :not_found and return
        end
        authorize! @project.organization, to: :read?
        render json: ::ProjectSerializer.new(@project, {}).serializable_hash
      end

      def create
        @org = Organization.find_by(name: params[:organization_id])
        authorize! @org, to: :can_create_project?

        @project = @org.projects.new(project_params)
        if @project.save
          render json: ::ProjectSerializer.new(@project, {}).serializable_hash
        else
          render json: @project.errors.full_messages, status: :bad_request
        end
      end

      def update
        @project = Project.find_by(external_id: params[:id])
        authorize! @project, to: :can_update?
        if @project.update(project_params)
          render json: ::ProjectSerializer.new(@project, {}).serializable_hash
        else
          render json: @project.errors.full_messages, status: :bad_request
        end
      end

      def destroy
        @project = Project.find_by(external_id: params[:id])
        authorize! @project, to: :can_update?
        if @project.delete
          render status: :no_content
        else
          render status: :internal_server_error
        end
      end

      private

      def project_params
        map_params(%i[name description])
      end
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < AuthenticatedController
  before_action :load_project, only: %i[edit show update destroy]

  before_action lambda {
    authorize! @organization, to: :can_create_project?
  }, only: [:create]

  before_action lambda {
    authorize! @project, to: :can_update?
  }, only: [:update]

  before_action lambda {
    authorize! @project, to: :can_destroy?
  }, only: [:destroy]

  def index
    @projects = @organization.projects
  end

  def show; end

  def new
    @project = @organization.projects.new
  end

  def edit; end

  def create
    @project = @organization.projects.new(project_params)
    if @project.save
      redirect_to project_path(@organization.name, @project.external_id)
    else
      render 'new'
    end
  end

  def update; end

  def destroy
    if @project.destroy
      redirect_to projects_path(@organization.name)
    else
      render :show
    end
  end

  private

  def load_project
    @project = @organization.projects.find_by(external_id: params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/helpers/api/v2/projects_helper.rb
# frozen_string_literal: true

module Api
  module V2
    module ProjectsHelper
    end
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/index.html.erb
<div class="mb-9">
  <div data-list='{"valueNames":["projectName","assignees","start","deadline","task","projectprogress","status","action"],"page":6,"pagination":true}'>
    <div class="row mb-4 gx-6 gy-3 align-items-center">
      <div class="col-auto">
        <h2 class="mb-0">Projects</h2>
      </div>
      <% if allowed_to?(:can_create_projects?, @organization) %>
      <div class="col-auto">
        <%= link_to "Create Project", new_project_path(@organization.name), class: "btn btn-primary px-5" %>
      </div>
      <% end %>
    </div>

    <div class="table-responsive scrollbar">
      <table class="table fs-9 mb-0 border-top border-translucent">
        <thead>
        <tr>
          <th class="sort white-space-nowrap align-middle ps-0" scope="col" data-sort="projectName" style="width:30%;">Name</th>
          <th class="sort align-middle ps-3" scope="col" data-sort="type" style="width:10%;">Description</th>
          <th class="sort align-middle ps-3" scope="col" data-sort="type" style="width:10%;">Teams</th>
          <th class="sort align-middle ps-3" scope="col" data-sort="id" style="width:10%;">Workspaces</th>
        </tr>
        </thead>
        <tbody class="list" id="project-list-table-body">
        <% @projects.each do |project| %>
          <tr class="position-static">
            <td class="align-middle time white-space-nowrap ps-0 projectName py-4"><a class="fw-bold fs-8" href="<%= project_path(@organization.name, project.external_id) %>"><%= project.name %></a></td>
            <td class="align-middle white-space-nowrap assignees ps-3 py-4">
              <%= project.description %>
            </td>
            <td class="align-middle white-space-nowrap assignees ps-3 py-4">
              <%= project.team_count %>
            </td>
            <td class="align-middle white-space-nowrap assignees ps-3 py-4">
              <%= project.workspace_count %>
            </td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<%#= form_with model: @organization do |form| %>
<%#= form.text_field :name %>
<%#= form.select :organization_type, ["personal", "business"] %>
<%#= form.submit %>
<%# end %>

<nav class="mb-3" aria-label="breadcrumb">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item"><a href="<%= projects_path(@organization.name) %>">Projects</a></li>
    <li class="breadcrumb-item active">New</li>
  </ol>
</nav>

<h2 class="mb-4">Create a project</h2>

<div class="row">
  <div class="col-xl-9">
    <%= form_with model: @project, class: "row g-3 mb-6" do |form| %>
      <div class="col-sm-6 col-md-8">
        <div class="form-floating">
          <%= form.text_field :name, class: "form-control" %>
          <label for="floatingInputGrid">Name</label>
        </div>
      </div>
      <div class="col-sm-6 col-md-8">
        <div class="form-floating">
          <%= form.text_field :description, class: "form-control" %>
          <label for="floatingInputGrid">Description</label>
        </div>
      </div>

      <div class="col-12 gy-6">
        <div class="row g-3 justify-content-end">
          <div class="col-auto">
            <%= link_to "Cancel", projects_path(@organization.name), class: "btn btn-phoenix-primary px-5" %>
          </div>
          <div class="col-auto">
            <%= form.submit "Create Project", class: "btn btn-primary px-5 px-sm-15" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<%= @project.name %>