config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Authentication / Authorizat
  use_doorkeeper
  use_doorkeeper_openid_connect
  devise_for :users
  get '.well-known/app.json', controller: :well_known, action: :app
  get '.well-known/terraform.json', controller: :well_known, action: :terraform
  get 'github/setup', controller: :github, action: :setup

  get 'app/*_', controller: :application, action: :index

  # Registry Routes
  namespace :registry, defaults: { format: :json } do
    namespace :v1 do
      scope 'modules', controller: 'modules' do
        get '/', action: :index
        get '/:namespace', action: :index
        get '/search', action: :search
        get '/:namespace/:name/:provider/versions', action: :versions
        get '/:namespace/:name/:provider/:version/download', action: :download, constraints: { version: %r{[^/]+} }
        get '/archive/:namespace/:name/:provider/:version/*.tar.gz', action: :archive, as: :archive,
                                                                     constraints: { version: %r{[^/]+} }
        get '/:namespace/:name/:provider/download', action: :download
        get '/:namespace/:name', action: :latest
        get '/:namespace/:name/:provider', action: :latest
        get '/:namespace/:name/:provider/:version', action: :show, constraints: { version: %r{[^/]+} }
        post '/:namespace/:name/:provider/:version', action: :create, constraints: { version: %r{[^/]+} }
      end
      scope 'providers', controller: 'providers' do
        post '/:namespace/:type/:version', action: :create, constraints: { version: %r{[^/]+} }
        get '/:namespace/:type/versions', action: :index
      end
    end
  end

  # API Routes
  namespace :api, defaults: { format: :json } do
    namespace :v2 do
      post :webhooks, action: :create, controller: 'webhooks'
      get :ping, action: :ping, controller: 'ping'
      get 'account/details', action: :show, controller: :account_details
      get 'organizations', action: :index, controller: :organizations
      get 'object/:key', action: :show, controller: :storage, as: :get_storage
      put 'object/:key', action: :update, controller: :storage, as: :upload_storage
      post 'organizations', action: :create, controller: :organizations
      scope '/organizations/:organization_id', as: :organization do
        get '', action: :show, controller: :organizations
        patch '', action: :update, controller: :organizations
        get 'entitlement-set', action: :entitlements, controller: :organizations
        get 'workspaces', action: :index, controller: :workspaces
        get 'workspaces/:id', action: :show, controller: :workspaces
        get 'runs/queue', action: :queue, controller: :organizations
        match 'tags', via: %i[get post delete], controller: :organizations

        get 'agent-pools', action: :index, controller: 'agents'
        post 'agent-pools', action: :create, controller: 'agents'

        get 'cloud-providers', action: :index, controller: :cloud_providers
        post 'cloud-providers', action: :create, controller: :cloud_providers

        get 'tasks', action: :index, controller: 'run_tasks'
        post 'tasks', action: :create, controller: 'run_tasks'

        get 'projects', action: :index, controller: :projects
        post 'projects', action: :create, controller: :projects

        get 'teams', action: :index, controller: :teams
        post 'teams', action: :create, controller: :teams

        get 'varsets', action: :index, controller: :variable_sets
        post 'varsets', action: :create, controller: :variable_sets

        get 'policies', action: :index, controller: :policies
        post 'policies', action: :create, controller: :policies

        post 'organization-memberships', action: :create, controller: :organization_memberships
        get 'organization-memberships', action: :index, controller: :organization_memberships

        post 'oauth-clients', action: :create, controller: :oauth_clients
        get 'oauth-clients', action: :index, controller: :oauth_clients

        post :workspaces, action: :create, controller: :workspaces

        get 'ssh-keys', action: :index, controller: :ssh_keys
        post 'ssh-keys', action: :create, controller: :ssh_keys

        get 'team-tokens', action: :list_team_tokens, controller: :authentication_tokens
        post 'authentication-token', action: :create_organization_token, controller: :authentication_tokens
        get 'authentication-token', action: :get_organization_token, controller: :authentication_tokens

        # Routes for registry modules
        get 'registry-modules', action: :index, controller: :modules
        post 'registry-modules', action: :create, controller: :modules
        get 'registry-modules/private/:namespace/:name/:provider', action: :show, controller: :modules, as: :show_module
        patch 'registry-modules/private/:namespace/:name/:provider', action: :update, controller: :modules
        post 'registry-modules/private/:namespace/:name/:provider/versions', action: :create,
                                                                             controller: :module_versions, as: :module_versions
        delete 'registry-modules/private/:namespace/:name', action: :destroy, controller: :modules
        delete 'registry-modules/private/:namespace/:name/:provider', action: :destroy,
                                                                      controller: :modules
        delete 'registry-modules/private/:namespace/:name/:provider/:version', action: :destroy,
                                                                               controller: :module_versions
        # Routes for registry providers
        get 'registry-providers', action: :index, controller: :providers
        post 'registry-providers', action: :create, controller: :providers
        get 'registry-providers/private/:namespace/:name', action: :show, controller: :providers
        delete 'registry-providers/:registry_name/:namespace/:name', action: :destroy,
                                                                     controller: :providers
        get 'registry-providers/private/:namespace/:name/versions/', action: :index,
                                                                     controller: :provider_versions, as: :provider_versions
        post 'registry-providers/private/:namespace/:name/versions', action: :create,
                                                                     controller: :provider_versions
        get 'registry-providers/private/:namespace/:name/versions/:version', action: :show,
                                                                             controller: :provider_versions, as: :provider_version
        delete 'registry-providers/private/:namespace/:name/versions/:provider_version', action: :destroy,
                                                                                         controller: :provider_versions
        post 'registry-providers/private/:namespace/:name/versions/:version/platforms', action: :create,
                                                                                        controller: :provider_version_platforms, constraints: { version: %r{[^/]+} }
        get 'registry-providers/private/:namespace/:name/versions/:version/platforms', action: :index,
                                                                                       controller: :provider_version_platforms, constraints: { version: %r{[^/]+} }, as: :provider_version_platforms
        get 'registry-providers/private/:namespace/:name/versions/:version/platforms/:os/:arch', action: :show,
                                                                                                 controller: :provider_version_platforms, constraints: { version: %r{[^/]+} }
        delete 'registry-providers/private/:namespace/:name/versions/:version/platforms/:os/:arch', action: :destroy,
                                                                                                    controller: :provider_version_platforms, constraints: { version: %r{[^/]+} }
      end
      get 'authentication-tokens/:token_id', action: :show, controller: :authentication_tokens
      delete 'authentication-tokens/:token_id', action: :destroy, controller: :authentication_tokens
      get 'state-versions/:id', action: :show, controller: :state_versions
      get 'state-version-outputs/:id', action: :show, controller: :state_version_outputs

      resources :workspaces, except: %i[index create] do
        member do
          post 'actions/lock', action: :lock, controller: :workspaces
          post 'actions/unlock', action: :unlock, controller: :workspaces
          post 'actions/force-unlock', action: :force_unlock, controller: :workspaces

          get 'state-versions', action: :index, controller: :state_versions
          post 'state-versions', action: :create, controller: :state_versions
          get 'current-state-version', action: :current, controller: :state_versions
          get 'current-state-version-outputs', action: :current_outputs, controller: :state_versions
          match 'relationships/tags', via: %i[get post delete], action: :tags, controller: :workspaces
          get :runs
          post :configuration_versions, action: :create, controller: :configuration_versions,
                                        path: 'configuration-versions'

          get :run_triggers, action: :index, path: 'run-triggers', controller: :run_triggers
          post :run_triggers, action: :create, path: 'run-triggers', controller: :run_triggers

          get :notification_configurations, action: :index, path: 'notification-configurations',
                                            controller: :notification_configurations
          post :notification_configurations, action: :create, path: 'notification-configurations',

app/models/registry_module.rb
# frozen_string_literal: true

class RegistryModule < ApplicationRecord
  belongs_to :organization

  has_many :registry_module_versions

  before_create -> { generate_id('mod') }
end

app/controllers/api/v2/registry_modules_controller.rb
# frozen_string_literal: true

module Api
  module V2
    class RegistryModulesController < Api::ApiController
      def index
        @org = Organization.find_by(name: params[:organization_id])
        authorize! @org, to: :show?
        @registry_modules = @org.registry_modules

        render json: ::RegistryModuleSerializer.new(@registry_modules, {}).serializable_hash
      end

      def show
        @org = Organization.find_by(name: params[:organization_id])
        authorize! @org, to: :show?
        @module = @org.registry_modules.where(
          # registry: "private",
          namespace: params[:namespace],
          name: params[:name],
          provider: params[:provider]
        ).first!

        render json: ::RegistryModuleSerializer.new(@module, {}).serializable_hash
      end

      def create
        @org = Organization.find_by(name: params[:organization_id])
        authorize! @org, to: :manage_modules?
        @registry_module = @org.registry_modules.new(module_params)
        @registry_module.namespace = @org.name
        @registry_module.status = 'pending'
        @registry_module.save!

        render json: ::RegistryModuleSerializer.new(@registry_module, {}).serializable_hash
      end

      def update
        head :not_implemented
      end

      def destroy
        # if params[:provider]
        # Delete just that provider?
        # else
        # Delete for all providers
        # end

        head :not_implemented
      end

      private

      def module_params
        map_params(%i[
                     name
                     provider
                   ])
      end
    end
  end
end

app/controllers/registry_modules_controller.rb
# frozen_string_literal: true

class RegistryModulesController < AuthenticatedController
  def index
    @modules = @organization.registry_modules
  end

  def show
    @module = @organization.registry_modules.find_by(external_id: params[:id])
  end

  def new; end

  def edit; end
  def create; end

  def update; end

  def destroy; end
end

app/helpers/api/v2/registry_modules_helper.rb
# frozen_string_literal: true

module Api
  module V2
    module RegistryModulesHelper
    end
  end
end

app/helpers/registry_modules_helper.rb
# frozen_string_literal: true

module RegistryModulesHelper
end

app/views/registry_modules/index.html.erb
<nav class="mb-3" aria-label="breadcrumb">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">Registry</li>
    <li class="breadcrumb-item">Modules</li>
  </ol>
</nav>

<div class="mb-9">
  <div data-list='{"valueNames":["projectName","assignees","start","deadline","task","projectprogress","status","action"],"page":6,"pagination":true}'>
    <div class="row mb-4 gx-6 gy-3 align-items-center">
      <div class="col-auto">
        <h2 class="mb-0">Modules</h2>
      </div>
      <div class="col-auto">
        <%= link_to "Create Module", new_registry_module_path(@organization.name), class: "btn btn-primary px-5" %>
      </div>
    </div>

    <div class="table-responsive scrollbar">
      <table class="table fs-9 mb-0 border-top border-translucent">
        <thead>
        <tr>
          <th class="sort white-space-nowrap align-middle ps-0" scope="col" data-sort="projectName" style="width:30%;">Namespace</th>
          <th class="sort white-space-nowrap align-middle ps-0" scope="col" data-sort="projectName" style="width:30%;">Name</th>
          <th class="sort white-space-nowrap align-middle ps-0" scope="col" data-sort="projectName" style="width:30%;">Provider</th>
          <th class="sort align-middle ps-3" scope="col" data-sort="type" style="width:10%;">Registry</th>
          <th class="sort align-middle ps-3" scope="col" data-sort="type" style="width:10%;">Status</th>
          <th class="sort align-middle ps-3" scope="col" data-sort="type" style="width:10%;">Latest Version</th>
          <th class="sort align-middle ps-3" scope="col" data-sort="type" style="width:10%;">Created At</th>
        </tr>
        </thead>
        <tbody class="list" id="project-list-table-body">
        <% @modules.each do |registry_module| %>
          <tr class="position-static">
            <td class="align-middle time white-space-nowrap ps-0 projectName py-4">
              <a class="fw-bold fs-8" href="<%= registry_module_path(@organization.name, registry_module.external_id) %>">
                <%= registry_module.namespace %>
              </a>
            </td>
            <td class="align-middle white-space-nowrap assignees ps-3 py-4">
              <%= registry_module.name %>
            </td>
            <td class="align-middle white-space-nowrap assignees ps-3 py-4">
              <%= registry_module.provider %>
            </td>
            <td class="align-middle white-space-nowrap assignees ps-3 py-4">
              private
            </td>
            <td class="align-middle white-space-nowrap start ps-3 py-4">
              <p class="mb-0 fs-9 text-body"><%= registry_module.status %></p>
            </td>
            <td class="align-middle white-space-nowrap deadline ps-3 py-4">
              <p class="mb-0 fs-9 text-body">N/A</p>
            </td>
            <td class="align-middle white-space-nowrap task ps-3 py-4">
              <p class="fw-bo text-body fs-9 mb-0"><%= registry_module.created_at %></p>
            </td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/registry_modules/show.html.erb
<nav class="mb-3" aria-label="breadcrumb">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">Registry</li>
    <li class="breadcrumb-item">Modules</li>
    <li class="breadcrumb-item active"><%= @module.namespace %>/<%= @module.name %>/<%= @module.provider %></li>
  </ol>
</nav>

<div class="mb-9">
  <div data-list='{"valueNames":["projectName","assignees","start","deadline","task","projectprogress","status","action"],"page":6,"pagination":true}'>
    <div class="row mb-4 gx-6 gy-3 align-items-center">
      <div class="col-auto">
        <h2 class="mb-0">Versions</h2>
      </div>
    </div>

    <div class="table-responsive scrollbar">
      <table class="table fs-9 mb-0 border-top border-translucent">
        <thead>
        <tr>
          <th class="sort white-space-nowrap align-middle ps-0" scope="col" data-sort="projectName" style="width:30%;">Version</th>
          <th class="sort align-middle ps-3" scope="col" data-sort="type" style="width:10%;">Status</th>
          <th class="sort align-middle ps-3" scope="col" data-sort="type" style="width:10%;">Source</th>
          <th class="sort align-middle ps-3" scope="col" data-sort="type" style="width:10%;">Created At</th>
        </tr>
        </thead>
        <tbody class="list" id="project-list-table-body">
        <% @module.registry_module_versions.each do |version| %>
          <tr class="position-static">
            <td class="align-middle time white-space-nowrap ps-0 projectName py-4">
              <%= version.version %>
            </td>
            <td class="align-middle white-space-nowrap assignees ps-3 py-4">
              <%= version.status %>
            </td>
            <td class="align-middle white-space-nowrap start ps-3 py-4">
              <%= version.source %>
            </td>
            <td class="align-middle white-space-nowrap deadline ps-3 py-4">
              <%= version.created_at %>
            </td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>